{
 "title": "Application",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "SHOW TAG VALUES  WITH KEY =\"instance\""
   },
   {
    "name": "env",
    "query": "SHOW TAG VALUES  WITH KEY =\"env\""
   }
  ]
 },
 "panels": [
  {
   "title": "Domain info monitoring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Scheduled",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "case_monitoring_scheduling-CaseMonitoring::Schedulers::ScheduleDomainInfoCheckJobs",
     "query": "SELECT sum(\"count\") FROM \"case_monitoring_scheduling-CaseMonitoring::Schedulers::ScheduleDomainInfoCheckJobs\" WHERE (\"account\" =~ /^$account$/ AND \"env\" =~ /^$env$/) AND $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "instance" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "finish" }
     ]
    },
    {
     "alias": "Error",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "case_monitoring_scheduling-CaseMonitoring::Schedulers::ScheduleDomainInfoCheckJobs",
     "query": "SELECT sum(\"count\") FROM \"case_monitoring_scheduling-CaseMonitoring::Schedulers::ScheduleDomainInfoCheckJobs\" WHERE (\"account\" =~ /^$account$/ AND \"env\" =~ /^$env$/) AND $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "error" }
     ]
    }
   ]
  },
  {
   "title": "Site aviability monitoring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Scheduled",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "case_monitoring_scheduling-CaseMonitoring::Schedulers::ScheduleSiteAvailabilityCheckJobs",
     "query": "SELECT sum(\"count\") FROM \"case_monitoring_scheduling-CaseMonitoring::Schedulers::ScheduleDomainInfoCheckJobs\" WHERE (\"account\" =~ /^$account$/ AND \"env\" =~ /^$env$/) AND $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "finish" }
     ]
    },
    {
     "alias": "Error",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "case_monitoring_scheduling-CaseMonitoring::Schedulers::ScheduleSiteAvailabilityCheckJobs",
     "query": "SELECT sum(\"count\") FROM \"case_monitoring_scheduling-CaseMonitoring::Schedulers::ScheduleDomainInfoCheckJobs\" WHERE (\"account\" =~ /^$account$/ AND \"env\" =~ /^$env$/) AND $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "error" }
     ]
    }
   ]
  },
  {
   "title": "Screenshots monitoring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Scheduled",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "case_monitoring_scheduling-CaseMonitoring::Schedulers::ScheduleScreenshotsComparingJobs",
     "query": "SELECT sum(\"count\") FROM \"case_monitoring_scheduling-CaseMonitoring::Schedulers::ScheduleDomainInfoCheckJobs\" WHERE (\"account\" =~ /^$account$/ AND \"env\" =~ /^$env$/) AND $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "finish" }
     ]
    },
    {
     "alias": "Error",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "case_monitoring_scheduling-CaseMonitoring::Schedulers::ScheduleScreenshotsComparingJobs",
     "query": "SELECT sum(\"count\") FROM \"case_monitoring_scheduling-CaseMonitoring::Schedulers::ScheduleDomainInfoCheckJobs\" WHERE (\"account\" =~ /^$account$/ AND \"env\" =~ /^$env$/) AND $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "error" }
     ]
    }
   ]
  },
  {
   "title": "Domain info",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Checked",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "domain_info",
     "query": "SELECT sum(\"count\") FROM \"domain_info\" WHERE (\"account\" =~ /^$account$/ AND \"env\" =~ /^$env$/ AND \"status\" = 'error') AND $timeFilter GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "finish" }
     ]
    },
    {
     "alias": "Exec time",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "domain_info",
     "query": "SELECT sum(\"count\") FROM \"domain_info\" WHERE (\"account\" =~ /^$account$/ AND \"env\" =~ /^$env$/ AND \"status\" = 'error') AND $timeFilter GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "execution_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "finish" }
     ]
    },
    {
     "alias": "Error",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "domain_info",
     "query": "SELECT sum(\"count\") FROM \"domain_info\" WHERE (\"account\" =~ /^$account$/ AND \"env\" =~ /^$env$/ AND \"status\" = 'error') AND $timeFilter GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "error" }
     ]
    }
   ]
  },
  {
   "title": "Site  aviability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "site_availability",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Workflow push",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Workflow copying",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "account_workflow_push",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "start" }
     ]
    },
    {
     "alias": "Workflow copying error",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "account_workflow_push",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "error" }
     ]
    },
    {
     "alias": "Workflow copying timing",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "account_workflow_push",
     "query": "SELECT mean(\"execution_time\") FROM \"account_workflow_push\" WHERE (\"account\" =~ /^$account$/ AND \"env\" =~ /^$env$/ AND \"status\" = 'finish') AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "execution_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "finish" }
     ]
    }
   ]
  },
  {
   "title": "Client brand reports",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Sended",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "client_brand_reports",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "finish" }
     ]
    },
    {
     "alias": "Error",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "client_brand_reports",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "finish" }
     ]
    },
    {
     "alias": "Scheduled",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "client_brand_reports",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "start" }
     ]
    },
    {
     "alias": "Avarage execution time",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "client_brand_reports",
     "select": [
      [
       { "params": [ "execution_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "finish" }
     ]
    }
   ]
  },
  {
   "title": "Mail box reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mail_box_read",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "finish" }
     ]
    }
   ]
  }
 ]
}